### ISSUE TITLE
Add a year sort to user's rating page

### ISSUE THREAD

**Issue by VINXIS** [apollo-dw/omdb#80] opened 2023-07-28 00:00 UTC
![image](https://github.com/apollo-dw/omdb/assets/18523454/47f6f40d-fe61-49ef-891f-275f6b898dbf)

I wanna filter by year 2 ;/

**Comment by apollo-dw** [comment] 2023-07-28 23:11
Duplicate of https://github.com/apollo-dw/omdb/issues/78

**Closed by apollo-dw** 2023-07-28 23:11 UTC
